dist:
  - trusty 

sudo:
  require
    
language: 
  - cpp

compiler:
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - llvm
      - lcov
      - kcov
      - cmake-data
      - cmake

before_script: |
  git clone https://github.com/RobotLocomotion/xfoil.git &&
  cd xfoil &&
  mkdir build &&
  cd build &&
  cmake .. &&
  sudo make -j install &&
  cd $TRAVIS_BUILD_DIR &&
  rm -rf xfoil

script:
  - mkdir build && cd build
  - cmake -DTESTING=1 ..
  - make
  - ./tests/unit_tests

    #after_success:
    #  - cd ${TRAVIS_BUILD_DIR}/build
    #  - kcov --exclude-pattern=gtest,/usr out tests/unit_tests
    #  - bash <(curl -s https://codecov.io/bash) && echo "Uploaded code coverage"
